### ISSUE TITLE
Previous item continues playing

### ISSUE THREAD

**Issue by Karambirov** [noreasonprojects/ModernAVPlayer#102]
Hello!

I'm learning iOS by writing Podcasts app. And I have 2 issues:

1. Previous item continues playing when I tap on another episode from my list.
I have noticed that when I tap "Stop" from Control Center and then tap on another episode, everything's working correctly.

2. I need to show how much time is left, but I couldn't find how can I get a duration of current media.

I would really appreciate it if you could help me. I'm using PlayerService as a wrapper for all of the player methods. And I present the player from EpisodesViewController. 
You can look at my code here: 
https://github.com/Karambirov/Podcasts/tree/feature/player-service

**Comment by JiceDessaint** [comment]
Hi @Karambirov 

1/ You create a new PlayerService on each on your PlayerDetailsViewModel, and so, a new ModernAVPlayer Instance. That is why it never stop. You loose reference to your players.
You must use a single instance of player to make it work. Ideally, you will be able to inject a single instance when you add DI to your project.
For now, maybe you can go old school and add a `static instance` singleton to your PlayerService to use.

2/ I'm not sure, but I believe you have to extract the duration of the episode from JSON you get from iTunes. try `feedItem.iTunes?.iTunesDuration` in in Episode initializer.

Hopes its help,

**Comment by Karambirov** [comment]
@JiceDessaint 
Thanks for your help)
I'll try to use a singleton for PlayerService. 
As for duration, I thought a media should have that property because AVPlayerItem does.

**Comment by raphrel** [comment]
Hi @Karambirov,

Use the `playerContext(didItemDurationChange itemDuration: Double?)` delegate method to get media duration. 
This method is triggered when ModernAVPlayer is in Loaded State = item is loaded in `AVPlayer`
I may get duration before, when AVPlayerItem is created but I choose this way.

**Comment by Karambirov** [comment]
@raphrel 
> Use the `playerContext(didItemDurationChange itemDuration: Double?)` delegate method to get media duration.

Could you explain how I can use this method? Should my service be the delegate of `PlayerContextDelegate` and implement all of its methods?

**Comment by raphrel** [comment]
I sent you a mail, this is not the right pace to discuss about it.
