### ISSUE TITLE
Fatal error: Executing on background thread

### ISSUE THREAD

**Issue by vbklv** [noreasonprojects/ModernAVPlayer#103]
I keep getting this error when trying to observe the player's state: **player.rx.state**

`
Fatal error: Executing on background thread. Please use 'MainScheduler.instance.schedule' to schedule work on main thread.: file /path/ios-app/Pods/RxSwift/RxSwift/Schedulers/MainScheduler.swift, line 43
`

Code (as per example):

```
private let player = ModernAVPlayer.init()

var stateObservable: Observable<ModernAVPlayer.State>

private let stateSubject = BehaviorSubject<ModernAVPlayer.State>(value: .initialization)

private let concurrentBackgroundScheduler = ConcurrentDispatchQueueScheduler(qos: .background)

let output: Output

struct Output {
    var stateObservable: Observable<ModernAVPlayer.State>
}

init() {
    output = Output(stateObservable: stateSubject.asObservable())

    player.rx.state
		.observeOn(concurrentBackgroundScheduler)
		.subscribe(stateSubject)
		.disposed(by: disposeBag)
}
```

**Comment by raphrel** [comment]
Hi @vbklv,

We use `[DelegateProxy](https://github.com/ReactiveX/RxSwift/blob/27b42ed7584a044d9ec6d7968c0d5f464abdcf93/RxCocoa/Common/DelegateProxy.swift#L18)` from RxCocoa library to create all corresponding observables.
You have explanation in the file about the main thread.

**Comment by vbklv** [comment]
Yes, managed to solve it by dispatching on main thread:

```
DispatchQueue.main.async { [weak self] in
	guard let self = self else { return }
	self.player.rx.state
		.subscribe(self.stateSubject)
		.disposed(by: self.disposeBag)
}
```
