### ISSUE TITLE
Example code creates retain cycle

### ISSUE THREAD

**Issue by valerianb** [noreasonprojects/ModernAVPlayer#104]
In the example, functions are passed to `map` or `subscribe(onNext:)`.
By referencing an instance method, you're actually making a strong reference to self and thus creating a retain cycle.

Example:
https://github.com/noreasonprojects/ModernAVPlayer/blob/2b3450e27c1fe8bc6bc571d48f466db0229a07fb/Example/ViewController.swift#L313

**Comment by raphrel** [comment]
you're right, I'll fix this.

**Comment by valerianb** [comment]
It's also the case on lines 249, 250, 262, 280 and 294 ;)

`createPositionRequest`, `formatPosition`, `setSliderPosition` and `setSeekPosition` (both methods don't set anything, the naming is a bit off) could be moved outside the class as they don't access `self` and could thus be simple private functions in that file (meaning outside of a class). That way you can keep the short current syntax.

For `setDebugMessage`, you can create an rx extension:
