### ISSUE TITLE
Sometimes player.rx.itemDuration returns NaN

### ISSUE THREAD

**Issue by dlpigpen** [noreasonprojects/ModernAVPlayer#106]
if I tap on the next, previous button in the player screen or remote control center. Sometimes player.rx.itemDuration return a NaN value. Thus, we cannot change the position of the slider time running.

```
// Display item duration
player.rx.itemDuration
.observeOn(concurrentBackgroundScheduler)
.filter { $0 != nil }
.map { String(format: "%.2f", $0!) }
.asDriver(onErrorJustReturn: "error")
.drive(onNext: setEndDurationTime)
.disposed(by: disposeBag)
```

```
  func setEndDurationTime(dur: String?) {
    // dur: NaN sometimes if we play quickly
        if let time = dur?.toDouble().playTimeString {
            self.lblEnd.text = time
        }
    }
    
```

**Comment by raphrel** [comment]
NaN can be return, depends on the media. What kind of media do you use ? extension ? 
Also, item duration is delivered in loaded state after duration had been fetch so it may take some time

https://github.com/noreasonprojects/ModernAVPlayer/blob/4f389093e8b74887c52b14d013fbf74686d8cc9d/Sources/Core/State/LoadedState.swift#L56

**Comment by dlpigpen** [comment]
@raphrel They are local mp3 files.  Sometimes it works well, but sometimes it does not. You can replicate by changing the next and previous track frequently from the remote center.

**Comment by dungInte** [comment]
I have the same issue. There is any way to fix it?

**Comment by barisyazganc** [comment]
Hi, I have the same issue once the duration is NaN it always NaN, is there any temp solution or fix on the way?

Note: this only happens only iOS versions below iOS13.. so %97 of crashes comes from iOS12 and %3 from iOS11

**Comment by raphrel** [comment]
Hi @barisyazganc, 

I would love to help but I need your context (media) to investigate. 

otherwise:
itemDuration is set once when item is loaded, only: `LoadedState` line `56` 
it comes from avplayeritem -> duration ->  seconds.
can you check in this location about duration return ?

I didn't do any computation of anything about this duration. just ask about the avplayer item just loaded his duration...

**Comment by barisyazganc** [comment]
> Hi @barisyazganc,
> 
> I would love to help but I need your context (media) to investigate.
> 
> otherwise:
> itemDuration is set once when item is loaded, only: `LoadedState` line `56`
> it comes from avplayeritem -> duration -> seconds.
> can you check in this location about duration return ?
> 
> I didn't do any computation of anything about this duration. just ask about the avplayer item just loaded his duration...

Hi again,

func modernAVPlayer(_ player: ModernAVPlayer, didItemDurationChange itemDuration: Double?)

I was using this method but when used it gives NaN sometimes.. when i remove this func and trt do get the duration in
func modernAVPlayer(_ player: ModernAVPlayer, didStateChange state: ModernAVPlayer.State)
check for state == .loaded 
duration is always true..

**Comment by raphrel** [comment]
ok, I am on it to make a demo queue example and check about this.

**Comment by raphrel** [comment]
@dlpigpen @barisyazganc @dungInte 

so I made a new branch:
https://github.com/noreasonprojects/ModernAVPlayer/tree/demo/simple-queue-example

Audio queue + remote command.
didn't see any bugs in item duration with my samples. (iOS 13.4.1 - iPhone XS)

can you try with yours ?

**Comment by raphrel** [comment]
New release with audio queue example #163, no bugs detected about nil duration.

Please create a branch to reproduce bugs you declared.
Thanks
