### ISSUE TITLE
Can't load videos from camera roll

### ISSUE THREAD

**Issue by Jarred-Sumner** [noreasonprojects/ModernAVPlayer#140]
When fetching videos from the camera roll, we call [`PHImageManager#requestAVAsset`](https://developer.apple.com/documentation/photokit/phimagemanager/1616935-requestavasset). 

But, `ModernAVPlayer` doesn't let us set an `AVURLAsset` object ourselves, so there doesn't seem to be a way of loading something from the camera roll without going through the underlying `AVPLayer`.

in `LoadingMediaState.swift`:
```swift
    private func createItem(with media: PlayerMedia) -> AVPlayerItem {
        let asset = AVURLAsset(url: media.url, options: media.assetOptions)
        return AVPlayerItem(asset: asset, automaticallyLoadedAssetKeys: ["playable", "duration"])
    }
```

Should I just go through the `AVPlayer` and let the KVO stuff from the `ModernAVPlayer` reconcile the difference?

**Comment by raphrel** [comment]
Hi Jarred,

Right now there is no public load method which accept `AVAsset` but you can definitely get the asset url and create a `ModernAVPlayerMedia` with it. It's not the best solution, but it should work.

I have to take some times to accept AVPlayerItem / AVAsset from the load public method..

**Comment by Jarred-Sumner** [comment]
Oh yeah, this works fine – I didn't realize it was okay to just use the URL returned from `PHImageManager`. I'm running into a different issue though, which I will create one for now.
