### ISSUE TITLE
The assetOptions propertry in ModernAVPlayerMedia should be a var varibale

### ISSUE THREAD

**Issue by mdfalcon104** [noreasonprojects/ModernAVPlayer#152]
In the development, I realize that this variable can be changed sometimes, for example we want to change the remoteURL, data image or other value. However, because this variable is a let variable, we are not able to do that. I suggest that it should be a var variable and update a new function like this. 

// ModernAVPlayerMedia.swift

` public var assetOptions: [String: Any]?`

```
public func setAssetOptions(asset: [String: Any]?) {
        self.assetOptions = asset
 }
```

Could you please revise in the next relesae?

**Comment by raphrel** [comment]
Hi,

`assetOptions` is only used in the AVURLAsset initializer: https://github.com/noreasonprojects/ModernAVPlayer/blob/4140f58113d7c5abfdd01010f6fbf0b80a204c82/Sources/Core/Services/AVPlayerItemInitService.swift#L42

and from what I could see, assetOptions data can be used at least with these keys: 
- `AVURLAssetPreferPreciseDurationAndTimingKey` 
- `AVURLAssetReferenceRestrictionsKey`
and certainly others

if you want to change url: create a new `PlayerMedia`
if you want to change image data from the current media, use the appropriate method for it: https://github.com/noreasonprojects/ModernAVPlayer/blob/c471de68aedfd5cddf35211c5b8f804f5e06c715/Sources/Core/ModernAVPlayer.swift#L143
