### ISSUE TITLE
Can you share/implement queue concept(including next/previous) in the example/by sample-code

### ISSUE THREAD

**Issue by rafattouqir** [noreasonprojects/ModernAVPlayer#155]
I'm trying to implement next/previous media, yet, was unable to do so using `ModernAVPlayer` library.

Code example:
`func modernAVPlayer(_ player: ModernAVPlayer, didItemPlayToEndTime endTime: Double) {
        self.next()
    }
func next() {
        self.player.load(media: nextMediaItem, autostart: true)
    }
`
Crash:
 Is related to `durationTimer`
Scenerio:
If I autoplay next media before delegate method `modernAVPlayer(player,didItemPlayToEndTime)` is called, then crash doesn't occur, however, if media is is finished playing and from delegate callback next  is invoked, then crash occured.

Expectation:
Try to share some example/sample code, so that next/previous media can be implemented like media queue concept.

**Comment by raphrel** [comment]
Hi @rafattouqir,

I may appreciate you make a pull request with your example using the `Simple Audio` template.
Is it possible from you side ?

Thanks

**Comment by raphrel** [comment]
Hi @rafattouqir,

I made a branch with simple audio queue here and option to play next track automatically:
https://github.com/noreasonprojects/ModernAVPlayer/tree/demo/simple-queue-example

you may had thread issues. I had to load the next media from the main thread.

reopen the issue if needed !
bye
