### ISSUE TITLE
ModernAVPlayerNowPlayingService.overrideInfoCenter Crashes

### ISSUE THREAD

**Issue by barisyazganc** [noreasonprojects/ModernAVPlayer#158]
Hi,
some of our users experiencing fatal crash in our app 

Crash is related to 
ModernAVPlayer
<compiler-generated> - Line 4362331420
ModernAVPlayerNowPlayingService.overrideInfoCenter(for:value:)

and 
NowPlayingService.swift - Line 92
closure #1 in ModernAVPlayerNowPlayingService.updateRemoteImage(url:) + 92

<compiler-generated> - Line 4362332792
thunk for @escaping @callee_guaranteed (@guaranteed Data?, @guaranteed NSURLResponse?, @guaranteed Error?) -> () + 4362332792

i think it happens when we provide the remoteimage..

i personally cant reproduce this crash but firebase crashlytics keeps popping this crash..

Crashed: NSOperationQueue 0x105d5fc40 (QOS: UNSPECIFIED)
EXC_BAD_ACCESS KERN_INVALID_ADDRESS 0x0000000000000000

we cant remove support for remoteimage because nowplaying info albumart is remote image and we dont use image cache so it must be downloaded using this method,

        let playerMetaData = ModernAVPlayerMediaMetadata(title: title,
                                                      albumTitle: albumTitle,
                                                      artist: artist,
                                                      image: placeHolderImageData,
                                                      remoteImageUrl: remoteImageURL)

player.updateMetadata(playerMetaData)

am i missing something or using this method wrong?

**Comment by raphrel** [comment]
Hi @barisyazganc,

I don't think you missed something.
`overrideInfoCenter` is called in a closure and should maybe use main thread instead of the closure thread. I don't have any other explication right now.

I created a new branch with a fix: 
https://github.com/noreasonprojects/ModernAVPlayer/tree/fix/metedata-remote-image-crash

can you use this branch in your podfile / spm to try and let me know ?
thanks!

**Comment by barisyazganc** [comment]
Thanks, will try this branch but not sure how to reproduce or check if crash has gone.. because i cant reproduce it in real device or simulator :(

**Comment by raphrel** [comment]
Understood, anyway I think those changes can't be bad.  
should be in the next release.

Let me know about your situation.

**Comment by barisyazganc** [comment]
Ok, thanks again :) will try and let you know the result...

**Comment by barisyazganc** [comment]
Hi,
I released an upgrade to our app including this change.. and i'm happy to say that for now there is no crash reported related to this issue so far!.. i will let you know again if a crash rises according to that issue..  i think this bug is fixed and ready to be released on next version :)

**Comment by raphrel** [comment]
#161 merged and ready to be part of the next release.

thanks again @barisyazganc  !
