### ISSUE TITLE
How to Remove NowPlayingInfo?

### ISSUE THREAD

**Issue by vkcldhkd** [noreasonprojects/ModernAVPlayer#165]
Hi. Thanks for making a good library. 

I know that NowPlayingInfo is updated automatically when I update ModernAVPlayerMediaMetadata, but I don't know how to remove NowPlayingInfo.

How to Remove NowPlayingInfo?

**Comment by raphrel** [comment]
hi @vkcldhkd,

What do you expect to remove in now playing info service ?

metadata are provided when created a media or update metadata manually

In this library, metadata concerns about title, album, artwork... you can check `PlayerMediaMetadata` protocol but **duration and isLive properties are set differently**.

I may change
`func updateMetadata(_ metadata: PlayerMediaMetadata)` to `func updateMetadata(_ metadata: PlayerMediaMetadata?)` 

is what you want ?

**Comment by raphrel** [comment]
you can try with this [branch](https://github.com/noreasonprojects/ModernAVPlayer/tree/feature/accept/optional-metadata)

**Comment by vkcldhkd** [comment]
I want remove commandCenter NowPlayingInfo!

**Comment by raphrel** [comment]
so use anywhere in your code
`MPNowPlayingInfoCenter.default().nowPlayingInfo = nil`

**Comment by vkcldhkd** [comment]
Thank you for your efforts :)
