### ISSUE TITLE
Crash on  PlayingState.swift - Line 193 PlayingState.routeAudioChanged(reason:) + 193

### ISSUE THREAD

**Issue by barisyazganc** [noreasonprojects/ModernAVPlayer#169]
Hi,

I came across a strange crash on Firebase...

Fatal Exception: NSInvalidArgumentException
An instance of AVPlayer cannot remove a time observer that was added by a different instance of AVPlayer.
PlayingState.routeAudioChanged(reason:)

Trace:

-[AVPlayer _removeAllLayers]

PlayingState.swift - Line 193
PlayingState.routeAudioChanged(reason:) + 193

PlayingState.swift - Line 65
partial apply for closure #1 in PlayingState.init(context:itemPlaybackObservingService:routeAudioService:interruptionAudioService:audioSession:) + 65

RouteAudioService.swift - Line 63
ModernAVPlayerRouteAudioService.audioRouteChanged(notification:) + 63

**Comment by raphrel** [comment]
hi @barisyazganc ,

I did a temporary fix branch.
This fix is not enough, I also need to prevent multiple callback call from playing state.

Before using flag pattern, I want to be sure there is a better solution.. I'm thinking about it

**Comment by barisyazganc** [comment]
Hi,

can you update the pod version so we can get it by pod update :)

**Comment by raphrel** [comment]
I'll make a new version at the end of August 2020.
you can still refer to develop branch from Podfile to have last adjustment.
thanks

**Comment by barisyazganc** [comment]
Hi,

Could you merge this from develop to master? because when SwiftPM used, choosing branch develop fails to add package because of Rx issue in SPM.. but it is fine when using version rules

**Comment by raphrel** [comment]
release update. sorry but it's hard to have time in this project...
