### ISSUE TITLE
signal SIGABRT on player.updateMetadata

### ISSUE THREAD

**Issue by barisyazganc** [noreasonprojects/ModernAVPlayer#171]
Hİ,

I just pod updated to 1.6.0 version but my app crashes on latest version on this line.. is there any code changes to that section? am i using it wrong in the latest version?

        let playerMetaData = ModernAVPlayerMediaMetadata(title: title,
                                                      albumTitle: albumTitle,
                                                      artist: artist,
                                                      image: placeHolderImageData,
                                                      remoteImageUrl: remoteImageURL)
        
        player.updateMetadata(playerMetaData)

Note: This code part executed on main thread with DispatchQueue.main.async {}

**Comment by raphrel** [comment]
this code is fine. may I have more context ? code, iPhone used, iOS version logtrace ... ?
thanks

**Comment by barisyazganc** [comment]
Nevermind it works now :) after pod update i had to uninstall app from device and do a clean build. now it works :)
