### ISSUE TITLE
prevTrackCommand, nextTrackCommand are not available

### ISSUE THREAD

**Issue by tauypaldiyev** [noreasonprojects/ModernAVPlayer#173]
prevTrackCommand, nextTrackCommand are not available even if I added them into remoteCommands. But skipBackwardCommand(), skipForwardCommand() commands work well. I want prev and next commands work, please help

**Comment by raphrel** [comment]
Hi,

there is a simple audio queue iOS example available in the sources with prev and next remote command 
did you check it out ?

**Comment by tauypaldiyev** [comment]
![photo5247082827818839747](https://user-images.githubusercontent.com/31894257/88299903-b48ede00-cd24-11ea-88e1-32003be2d70d.jpg)
![Снимок экрана 2020-07-23 в 20 38 51](https://user-images.githubusercontent.com/31894257/88299931-bc4e8280-cd24-11ea-8be2-f4468e236176.png)

Yes, I checked. In photo it is shown how did I implemented needed commands, in my case prev/next commands. But on the player these buttons are not available/clickable

**Comment by raphrel** [comment]
Check ModernAVPlayerRemoteCommandFactory.swift file, line `146` and `157`

`nextTrackCommand` and `prevTrackCommand` are not enable by default. my bad, I have to change it.

**Comment by raphrel** [comment]
It make no sense I provide you these remote command by default. You have to provide your own logic in handler.
Check the associated pull request and use Simple Audio Queue example as reference.
