### ISSUE TITLE
Paused audio not resuming after phone call

### ISSUE THREAD

**Issue by barisyazganc** [noreasonprojects/ModernAVPlayer#174]
Hi,

When a call recieved, or switched to camera app to take video, after interruption endded audio is not started.. i'm testing on iOS 13.6..

IS there a way to override interruption callbacks?. is The code below responsible for not resuming the audio playback after interruption?

`    /*
     Do not set any call back on interruption ended when user play from another app
    */
    private func pauseByInterruption() {
        let state = PausedState(context: context)
        if !audioSession.secondaryAudioShouldBeSilencedHint {
            state.onInterruptionEnded = { [weak state] in state?.play() }
        }
        changeState(state: state)
    }`

**Comment by barisyazganc** [comment]
Update: audio resumes if app is on foreground, but if the app is in background it doesnt resume

**Comment by barisyazganc** [comment]
Hi A little update again;

If i changed the line 56 in AudioSessionService.swift 
`try audioSession.setCategory(category, mode: .default, options: [])`

with
`try audioSession.setCategory(category, mode: .default, options: [.mixWithOthers])`

it will resume playback after an interruption while app is in background..

is it possible to make options optional like setting options in config?

**Comment by raphrel** [comment]
Hi @barisyazganc,

thanks for this ! I'm gonna check this week and make modification

**Comment by barisyazganc** [comment]
Hi @raphrel 

Thanks, by the way i didnt have much time to debug more but it seems that .mixWithOthers solves the problem but can introduces more bugs im not sure

**Comment by raphrel** [comment]
.mixWithOthers is not the good solution in my mind.
I have to understand deeper why resume process is not called... 
let's get in touch about this

**Comment by barisyazganc** [comment]
Hi,

i'm on your side but some posts on stackoverflow strongly suggests .mixWithOthers in order to resume playback when app is in background during interruption.. i will search more on this and also audio did not resume when switching between other apps (like playing video on facebook app) but it seems spotify handles them correctly, i'm not sure 

the post: https://stackoverflow.com/questions/38800204/how-to-resume-audio-after-interruption-in-swift/38809220

**However if you are using an interruption handler, .play() must NOT be invoked within handleInterruption() as doing so does NOT guarantee play to resume & seems to prevent audioPlayerEndInterruption() to be called (see docs). Instead .play() must be invoked within audioPlayerEndInterruption() (any of its 3 versions) to guarantee resumption.

Furthermore, AVAudioSession must be give option .MixWithOthers noted by @Simon Newstead if you want your app to resume play after interruption when your app is in the background. It seems that if a user wants the app to continue playing when it goes into the background, it is logical to assume the user also wants the app to resume playing after an interruption while the app is in the background. Indeed that is the behaviour exhibited by the Apple Music app.**
