### ISSUE TITLE
Possible support for tvOS

### ISSUE THREAD

**Issue by barisyazganc** [noreasonprojects/ModernAVPlayer#176]
Hi,

is it possible to support tvOS without any development? i want to use modernavplayer with my tvOS target but pod install says its not compatible with tvOS

**Comment by raphrel** [comment]
Hi,

I think I use some framework / methods not available for tvOS. It's been a long time I didn't check...
don't think it's a lot of work but need some development.
it's holiday times, and I have not so much time these days to make any adjustment/ I'm sorry but if you want to make a pull request, you're welcome !

**Comment by barisyazganc** [comment]
Hi,

thanks, i will check if can make it compatible with tvOS... It will be great to have this wonderfull library available on tvOS! :) keep in touch...

**Comment by raphrel** [comment]
hi @barisyazganc, did you try ??
