### ISSUE TITLE
How to repeat track on loop?

### ISSUE THREAD

**Issue by ArbabR** [noreasonprojects/ModernAVPlayer#64]
Hi 

How can we apply loop on a track to repeat?

Thanks

**Comment by ArbabR** [comment]
Hi @raphrel 

Thanks for checking this out. Any rough idea when this will be done?

**Comment by raphrel** [comment]
Hi @ArbabR,

thanks for your suggestion, I'm gonna try a version this week.

**Comment by ArbabR** [comment]
Ok awesome! thanks

**Comment by raphrel** [comment]
a feature is coming: https://github.com/noreasonprojects/ModernAVPlayer/pull/68

**Comment by ArbabR** [comment]
This is awesome! thanks a lot 👍

**Comment by raphrel** [comment]
version 0.13.0 include loop mode 👌
https://github.com/noreasonprojects/ModernAVPlayer/tree/0.13.0

**Comment by ArbabR** [comment]
Thanks much appreciated 👍
