### ISSUE TITLE
Convert time to hours:minutes:seconds

### ISSUE THREAD

**Issue by ArbabR** [noreasonprojects/ModernAVPlayer#78]
Can we please convert current time and end duration time to this format

hours:minutes:seconds

01:25:42

![Uploading Simulator Screen Shot - iPhone 8 Plus - 2018-10-07 at 23.01.09.png…]()

**Comment by raphrel** [comment]
Hi,

This is more a UI request, everyone need a different string format.
So I may not include this request in the library.

Anyway, you can simply use `DateComponentsFormatter`: https://stackoverflow.com/a/43890305/5144603

**Comment by ArbabR** [comment]
Hi 

Sure I'll look into it. Thanks for the help.
