### ISSUE TITLE
Please add support for caching

### ISSUE THREAD

**Issue by satishVekariya** [noreasonprojects/ModernAVPlayer#93]

**Comment by raphrel** [comment]
Can you be more specific about your expectations ?

**Comment by satishVekariya** [comment]
Local disk caching,
user only needs to stream a file once and after that it can be played from a local cache

**Comment by raphrel** [comment]
sure, it's a big feature to implement.
I'm gonna think about it.

**Comment by mirasaujan** [comment]
Hey there, 
Any updates? I found several drop in solutions for caching assets. They work with AVPlayerItems though. Could you add support to play/load PlayerMedia with playerItem?

**Comment by raphrel** [comment]
Hi,

I know it is a main feature for this library but it's hard for me to manage all requirements..
Do you have any links to solutions you have found ?

Also, not interested to do a pull request ?

thanks

**Comment by mirasaujan** [comment]
https://andreygordeev.com/2018/03/31/cache-avplayeritem/
https://github.com/neekeetab/CachingPlayerItem
https://github.com/vitoziv/VIMediaCache

could you elaborate on the requirements?

**Comment by satishVekariya** [comment]
https://github.com/muhku/FreeStreamer

**Comment by raphrel** [comment]
ok so 2 things:

* Caching feature have to be done from an external service like CachingPlayerItem or other library..  It's not the responsability of the player.
* ModernAVPlayer to consume caching media have to accept AVPlayerItem when loading media.

So for now, **I'm going to think about the second point**. As this, you'll use your favorite caching service with the player. _Later, I may try to write my own caching service..._

**Comment by mirasaujan** [comment]
You can try to restrict playerItem feed to PlayerMedia, only to those whose status == .readyToPlay

**Comment by zackperdue** [comment]
What's the status on this? Is anybody looking into this yet?

**Comment by raphrel** [comment]
on my way, should be done this week ! 
The lib will accept AVPlayerItem and url format.

**Comment by zackperdue** [comment]
Awesome! Let me know if there’s anything to do to help.

On Jan 27, 2020, at 12:16 PM, ankierman <notifications@github.com> wrote:

on my way, should be done this week !
The lib will accept AVPlayerItem and url format.

**Comment by zackperdue** [comment]
Hi @raphrel any updates on this improvement? I'm looking to upgrade :) 

If you need help with anything please let me know and I can pitch it. 

Go ahead and upload your branch or whatever.

**Comment by raphrel** [comment]
Hi, 
sorry kind of busy these past days. I try to finish this week end !

**Comment by raphrel** [comment]
new release #151 is out !
create a media from AVPlayerItem is available 😅
